# serverless.yml
plugins:
  - serverless-offline
  - serverless-webpack

service: my-express-application

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: ap-northeast-1
 
functions:
  app:
    handler: src/app.handler
    timeout: 30
    memorySize: 1024
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

custom:
  webpack:
    packager: npm
    includeModules: true
  prune:
    automatic: true
    number: 3